# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ticket-masala-api'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://+:8080"
  MASALA_CONFIG_PATH = "/app/inputs/config"
  MASALA_DB_PATH = "/app/inputs/data/masala.db"
  MASALA_AUTOLOGIN_EMAIL = "admin@ticketmasala.com"
  MASALA_AUTOLOGIN_PASSWORD = "Admin123!"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[mounts]
  source = "masala_data"
  destination = "/app/inputs"
  initial_size = "1gb"
